//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avion()
        {
            this.ReservasVuelo = new HashSet<ReservasVuelo>();
            this.Vuelo1 = new HashSet<Vuelo>();
        }
    
        public int CodigoAvion { get; set; }
        public int CodigoAerolinea { get; set; }
        public int CodigoVuelo { get; set; }
        public int CodigoAeropuerto { get; set; }
        public int Capacidad { get; set; }
    
        public virtual Aerolinea Aerolinea { get; set; }
        public virtual Aeropuerto Aeropuerto { get; set; }
        public virtual Vuelo Vuelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservasVuelo> ReservasVuelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vuelo> Vuelo1 { get; set; }
    }
}
