//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipaje
    {
        public int CodigoEquipaje { get; set; }
        public int CodigoUsuario { get; set; }
        public int Costo { get; set; }
        public int Peso { get; set; }
        public int CodigoAvion { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
