//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RESERVAS_ULACIT_3C2021Entities : DbContext
    {
        public RESERVAS_ULACIT_3C2021Entities()
            : base("name=RESERVAS_ULACIT_3C2021Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Error> Error { get; set; }
        public virtual DbSet<Estadistica> Estadistica { get; set; }
        public virtual DbSet<Habitacion> Habitacion { get; set; }
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<Sesion> Sesion { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Aerolinea> Aerolinea { get; set; }
        public virtual DbSet<Aeropuerto> Aeropuerto { get; set; }
        public virtual DbSet<Avion> Avion { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Equipaje> Equipaje { get; set; }
        public virtual DbSet<Pago> Pago { get; set; }
        public virtual DbSet<ReservasVuelo> ReservasVuelo { get; set; }
        public virtual DbSet<Vuelo> Vuelo { get; set; }
    }
}
